### ISSUE TITLE
Integrating Typescript

### ISSUE THREAD

**Issue by bragur** [mstn/apollo-local-network-interface#1] opened 2016-12-19 12:08 UTC
Hey there. Was very happy to find this repo, but am having problems integrating it with my React Native project. I've set up a custom local schema, wrapping an existing REST API, which I intended to use with Apollo and connect to Redux. But this isn't really working for me as I'm not experienced enough to really know how to use Typescript with my current project and how to properly connect it. How would one go about adding this to a project?

**Comment by mstn** [comment] 2016-12-30 13:27
Hi, thanks for stopping by and sorry for the late reply. I have not published the package yet because it is a trivial piece of code and I was not sure if it makes sense. As you can see from the README file, I followed a common well-known pattern which is easy to reproduce in your code without using Typescript (if you use ES6, just ignore types). I do not have experience with React Native, but in the credit section you can find a reference to a blog where the author used a very similar network interface in RN. Otherwise, if you explain me what kinds of problems you are experiencing, I could try to guess a solution.

**Comment by mstn** [comment] 2017-06-21 12:30
Hey @bragur, I found a bit of time to fix some problems. You can try the package with 

`npm install mstn:apollo-local-network-interface#v1.0.0`

Please feel free to write me back if you have any problem. Until then, I will close the issue.

**Closed as completed by mstn** 2017-06-21 12:30 UTC
